[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=../node_modules/@openzeppelin/",
    "@uniswap/=../node_modules/@uniswap/",
    "hardhat/=../node_modules/hardhat/",
]
allow_paths = ["../node_modules"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
